mutation CreateUser($id: String!, $email: String!, $fullName: String!, $studentId: String, $facultyReference: String, $certificateUrl: String!, $gender: String) @auth(level: PUBLIC) {
  user_insert(data: {
    id: $id,
    email: $email,
    fullName: $fullName,
    studentId: $studentId,
    facultyReference: $facultyReference,
    certificateUrl: $certificateUrl,
    verificationStatus: "pending",
    gender: $gender
  })
}

mutation UpdateUserStatus($id: String!, $status: String!) @auth(level: PUBLIC) {
  user_update(id: $id, data: {verificationStatus: $status})
}

mutation CreateHelpRequest(
  $title: String!
  $description: String!
  $budget: Float!
  $requesterId: String!
  $category: String
  $urgency: String
  $deadline: String
) @auth(level: PUBLIC) {
  helpRequest_insert(data: {
    title: $title
    description: $description
    budget: $budget
    requesterId: $requesterId
    category: $category
    urgency: $urgency
    deadline: $deadline
  })
}

mutation CreateApplication(
  $helpRequestId: UUID!
  $applicantId: String!
  $priceOffer: Float!
  $message: String!
) @auth(level: PUBLIC) {
  application_insert(data: {
    helpRequestId: $helpRequestId
    applicantId: $applicantId
    priceOffer: $priceOffer
    message: $message
    status: "PENDING"
  })
}

mutation UpdateApplicationStatus($id: UUID!, $status: String!) @auth(level: PUBLIC) {
  application_update(id: $id, data: {status: $status})
}

mutation CreateConversation(
  $applicationId: UUID!
  $posterId: String!
  $applicantId: String!
) @auth(level: PUBLIC) {
  conversation_insert(data: {
    applicationId: $applicationId
    posterId: $posterId
    applicantId: $applicantId
  })
}

mutation CreateMessage(
  $conversationId: UUID!
  $senderId: String!
  $content: String!
) @auth(level: PUBLIC) {
  message_insert(data: {
    conversationId: $conversationId
    senderId: $senderId
    content: $content
  })
}
