type User @table(key: "id") {
  id: String!
  email: String!
  fullName: String!
  studentId: String
  facultyReference: String
  certificateUrl: String!
  verificationStatus: String!
  preferredRole: String
  gender: String
}

type Category @table {
  name: String!
  description: String
}

type Service @table {
  title: String!
  description: String!
  price: Float!
  category: Category!
  provider: User!
}

type HelpRequest @table {
  title: String!
  description: String!
  budget: Float!
  requester: User!
  category: String
  urgency: String
  deadline: String
}

type Review @table {
  rating: Int!
  comment: String!
  reviewer: User!
  targetUser: User!
}

type Application @table {
  helpRequest: HelpRequest!
  applicant: User!
  priceOffer: Float!
  message: String!
  status: String! # pending, approved, rejected
  createdAt: Date! @default(expr: "request.time")
}

type Conversation @table {
  application: Application!
  poster: User!
  applicant: User!
  createdAt: Date! @default(expr: "request.time")
}

type Message @table {
  conversation: Conversation!
  sender: User!
  content: String!
  createdAt: Date! @default(expr: "request.time")
}
